### ISSUE TITLE
Scale out with marmot

### ISSUE THREAD

**Issue by gedw99** [gobeli/pocketbase-htmx#1]
This is a great example .

would like to add the needed docker to allow it to scale out on fly.io.

 it setups up the db in multi master fashion with only a docker file .

https://github.com/maxpert/marmot-pocketbase-flyio Has the docker file which we can adapt

**Comment by gobeli** [comment]
Thanks for the idea, but i don't think it's really in the scope of this project. It's just supposed to be a small example without deployment, scaling etc.
